repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--output-format=concise"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--explicit-package-bases", "src", "tests"]
        pass_filenames: false
        additional_dependencies:
          - numpy>=1.26
          - pandas>=2.1
          - typing-extensions>=4.9
          - pytest

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
