site_name: PyCircuitKit
site_description: Circuit simulation helpers and analysis utilities
site_author: lgili
repo_name: lgili/PyCircuitKit
site_url: https://lgili.github.io/PyCircuitKit/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            # Extra options must be nested under `extra` to avoid deprecation
            # warnings. `search_path` tells the python handler where to look
            # for the local package in a root-layout project.
            extra:
              search_path:
                - .

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Concepts: concepts.md
  - Examples:
      - Overview: examples.md
      - Monte Carlo example: monte-carlo-example.md
  - Examples Gallery: examples-gallery.md
  - Components: components.md
  - Components Quickstart: components-quickstart.md
  - Guides:
      - Circuit Preview: preview.md
    - Engines & Backends: engines.md
      - Sweeps and STEP: sweeps-step.md
      - Monte Carlo: monte-carlo.md
      - AC Stability: ac-stability.md
      - Op-Amp Stability: opamp-stability.md
      - Device Models: device-models.md
      - LTspice Integration: ltspice-import.md
      - Component Library: components-library.md
      - Plots: plots.md
      - Troubleshooting: troubleshooting.md
  - API guidance: api-reference.md
  - Cookbook: cookbook.md
  - API Reference:
      - Core: reference/core.md
      - IO: reference/io.md
      - Analysis: reference/analysis.md
extra_css:
  - assets/stylesheets/extra.css
extra: {}
