site_name: Circuit Toolkit
site_description: Unified Python orchestration for SPICE simulations
site_author: lgili
repo_name: lgili/CircuitToolkit
site_url: https://lgili.github.io/CircuitToolkit/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            # Extra options must be nested under `extra` to avoid deprecation
            # warnings. `search_path` tells the python handler where to look
            # for the local package in a root-layout project.
            extra:
              search_path:
                - .

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Concepts: concepts.md
  - Components:
      - Overview: components.md
      - Quick reference: components-quickstart.md
      - Device models: device-models.md
      - Library status (refresh soon): components-library.md
  - Engines: engines.md
  - Data I/O: unified-io.md
  - Sweeps: sweeps-step.md
  - Monte Carlo: monte-carlo.md
  - Cookbook: cookbook.md
  - Examples:
      - Overview: examples.md
      - Usage: examples-usage.md
      - Gallery: examples-gallery.md
      - Monte Carlo assets: monte-carlo-example.md
  - Guides:
      - Circuit preview: preview.md
      - Plotting: plots.md
      - LTspice integration: ltspice-import.md
      - Analog mux: mux-enable-ports.md
      - CLI & CI: cli-ci.md
      - Reporting: reporting.md
      - Environment doctor: doctor.md
      - Troubleshooting: troubleshooting.md
  - Legacy notes:
      - AC stability (refresh soon): ac-stability.md
      - Op-amp stability (refresh soon): opamp-stability.md
      - Old roadmap (M1/M2): core-contracts.md
  - API guidance: api-reference.md
  - API reference:
      - Core: reference/core.md
      - IO: reference/io.md
      - Analysis: reference/analysis.md
extra_css:
  - assets/stylesheets/extra.css
extra: {}
