repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: uv run ruff check .
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format .
        language: system
        types: [python]
      - id: mypy
        name: Mypy type-check
        entry: uv run mypy src tests
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
