name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install NGSpice (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y ngspice
          ngspice -v || true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff mypy pytest pytest-cov
      - name: Ruff (format + lint)
        run: |
          ruff version
          ruff format .
          ruff check .
      - name: Mypy (type-check)
        run: |
          mypy --version
          mypy --explicit-package-bases src tests
      - name: Pytest
        env:
          PYTHONWARNINGS: default
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=cat --cov-report=term-missing

  ngspice-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install NGSpice (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y ngspice
          ngspice -v || true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov
      - name: Pytest (with ngspice)
        env:
          PYTHONWARNINGS: default
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=cat --cov-report=term-missing

  generate-demo-images:
    runs-on: ubuntu-latest
    needs: lint-type-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install plotting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install matplotlib scipy pandas
      - name: Install project (editable)
        run: |
          python -m pip install -e .[viz] --verbose
      - name: Generate demo images
        run: |
          PYTHONPATH=src python examples/mc_demo_plots.py
      - name: Upload demo images
        uses: actions/upload-artifact@v4
        with:
          name: demo-doc-images
          path: docs/assets/examples/
