name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ngspice graphviz
          ngspice -v || true
      - name: Sync project + doc dependencies
        run: |
          uv sync --frozen --group dev --extra viz --extra data
          uv pip install -r docs-requirements.txt

      - name: Verify import (fail early)
        run: |
          uv run python -c "import importlib.util; print('find_spec spicelab ->', importlib.util.find_spec('spicelab'))"
          uv run python -c "import spicelab; print('spicelab imported OK:', getattr(spicelab, '__file__', None))"
      - name: Generate example assets
        env:
          MPLBACKEND: Agg
        run: |
          uv run python examples/mc_demo_plots.py
          uv run python examples/report_demo.py

      - name: Build site
        run: uv run python -m mkdocs build --strict
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
