name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs-requirements.txt
      - name: Install project (editable)
        run: |
          python -m pip install -e . --verbose

      - name: Ensure PYTHONPATH includes src
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

      - name: Verify import (fail early)
        run: python -c "import importlib, traceback, sys; print('find_spec cat ->', importlib.util.find_spec('cat')); import cat; print('cat imported OK:', getattr(cat, '__file__', None))"

      - name: Build site
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python -m mkdocs build --strict
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
